name: 'Check Project Release Verification'
description: 'Github Action to check if a project release was verified.'

runs:
  using: 'node12'
  main: 'index.js'

inputs:
  token:
    required: true
  release_number:
    required: true

outputs:
  workflow:
    description: 'The passing workflow if found.'
  job:
    description: 'The job of the passing workflow if found.'
  run_id:
    description: 'The run ID of the passing workflow if found.'
  run_url:
    description: 'The URL of the passing workflow if found.'
